theme = "onedark"

[editor]
line-number = "relative"
mouse = true
scrolloff = 8
rulers = [80, 120]
completion-trigger-len = 1
auto-save = false
idle-timeout = 400
preview-completion-insert = true
completion-replace = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 10

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
render = "all"
characters = { space = "·", nbsp = "⍽", tab = "→", newline = "⏎", tabpad = "·" }

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.smart-tab]
enable = true
supersede-menu = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["file-encoding"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "diagnostics", "workspace-diagnostics"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"
"<" = ">"

[keys.normal]
# Quick save
C-s = ":w"
# Quick quit
C-q = ":q"
# Center cursor
C-c = ["collapse_selection", "keep_primary_selection", "align_view_center"]
# Format document
C-A-l = ":format"
# File tree
C-e = ":open ~/.config/helix/runtime/queries"
# Multiple cursors
C-d = ["move_char_right", "extend_till_char"]
# Quick actions
space.q = ":buffer-close"
space.Q = ":buffer-close-others"
space.w = ":w"
space.W = ":wa"
# LSP
space.r = "rename_symbol"
space.a = "code_action"
space.h = "hover"
g.d = "goto_definition"
g.r = "goto_reference"
g.i = "goto_implementation"
g.t = "goto_type_definition"
# Diagnostics
space.d = "diagnostics_picker"
"[" = { d = "goto_prev_diag", D = "goto_first_diag" }
"]" = { d = "goto_next_diag", D = "goto_last_diag" }

[keys.insert]
# Quick save in insert mode
C-s = ["normal_mode", ":w", "insert_mode"]
# Auto completion
C-space = "completion"
# Snippet navigation
C-j = "jump_forward"
C-k = "jump_backward"