theme = "onedark"

[editor]
line-number = "relative"
mouse = true
scrolloff = 8
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┊"

[editor.soft-wrap]
enable = true

[keys.normal]
# Quick save
C-s = ":w"
# Quick quit
C-q = ":q"
# Center cursor
C-c = ["collapse_selection", "keep_primary_selection", "align_view_center"]

[keys.insert]
# Quick save in insert mode
C-s = ["normal_mode", ":w", "insert_mode"]