function cm-help --description "Show chezmoi aliases and commands"
    echo "Chezmoi Aliases"
    echo "==============="
    echo ""
    echo "Quick Commands:"
    echo "  cm          - chezmoi"
    echo "  cma         - Apply changes (with prompts)"
    echo "  cmaf        - Apply changes (force, no prompts)"
    echo "  cmd         - Show diff of changes"
    echo "  cme         - Edit a file in chezmoi source"
    echo "  cmcd        - Change to chezmoi source directory"
    echo "  cms         - Show status of managed files"
    echo "  cmu         - Update from remote repository"
    echo ""
    echo "Common Workflows:"
    echo "  cmd && cma  - Review changes then apply"
    echo "  cmcd        - Go to dotfiles directory"
    echo "  cme <file>  - Edit a managed file"
    echo ""
    echo "Examples:"
    echo "  cmd ~/.config/fish/config.fish    - See changes for specific file"
    echo "  cma ~/.tmux.conf                  - Apply just one file"
    echo "  cmaf --exclude=scripts            - Apply all except scripts"
    echo ""
    echo "Your chezmoi source: "(chezmoi source-path)
end