# Starship prompt configuration

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
style = "bold red"

[nodejs]
symbol = " "
style = "bold green"

[rust]
symbol = " "
style = "bold red"

[python]
symbol = " "
style = "bold yellow"

[docker_context]
symbol = " "
style = "bold blue"

[package]
symbol = "󰏗 "
style = "bold 208"

[golang]
symbol = " "
style = "bold cyan"

[java]
symbol = " "
style = "bold red"

[lua]
symbol = " "
style = "bold blue"

[memory_usage]
symbol = "󰍛 "
style = "bold dimmed white"
disabled = true

[aws]
symbol = "󰸏 "
style = "bold orange"

[kubernetes]
symbol = "󱃾 "
style = "bold blue"
disabled = false

[time]
disabled = false
time_format = "%R"
style = "bold white"
format = "[$time]($style)"

[fill]
symbol = " "